"""
utils.py — Helper utilities for ContentFlow AI
  generate_pdf(draft, title) → bytes
"""


def generate_pdf(draft: str, title: str = "Article") -> bytes:
    """
    Convert a markdown-style draft to a styled PDF using reportlab.
    Falls back to UTF-8 encoded plain text if reportlab is not installed.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        )
        import io

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=2.5 * cm,
            rightMargin=2.5 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
            title=title,
        )

        # ── Styles ────────────────────────────────────────────────────────────
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "CFTitle",
            parent=styles["Title"],
            fontSize=24,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#1e293b"),
            spaceAfter=6,
            leading=28,
        )
        subtitle_style = ParagraphStyle(
            "CFSubtitle",
            parent=styles["Normal"],
            fontSize=11,
            fontName="Helvetica",
            textColor=colors.HexColor("#64748b"),
            spaceAfter=18,
        )
        h2_style = ParagraphStyle(
            "CFH2",
            parent=styles["Heading2"],
            fontSize=15,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#1e293b"),
            spaceBefore=18,
            spaceAfter=6,
            leading=20,
        )
        h3_style = ParagraphStyle(
            "CFH3",
            parent=styles["Heading3"],
            fontSize=13,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#334155"),
            spaceBefore=12,
            spaceAfter=4,
            leading=17,
        )
        body_style = ParagraphStyle(
            "CFBody",
            parent=styles["Normal"],
            fontSize=11,
            fontName="Helvetica",
            textColor=colors.HexColor("#334155"),
            leading=18,
            spaceAfter=8,
        )
        bullet_style = ParagraphStyle(
            "CFBullet",
            parent=body_style,
            leftIndent=16,
            spaceAfter=5,
        )
        footer_style = ParagraphStyle(
            "CFFooter",
            parent=styles["Normal"],
            fontSize=9,
            fontName="Helvetica",
            textColor=colors.HexColor("#94a3b8"),
            spaceAfter=0,
        )

        # ── Build story ───────────────────────────────────────────────────────
        story = []

        # Header
        story.append(Paragraph(title, title_style))
        story.append(Paragraph("Generated by ContentFlow AI", subtitle_style))
        story.append(HRFlowable(
            width="100%", thickness=1,
            color=colors.HexColor("#e2e8f0"),
            spaceAfter=16,
        ))

        # Parse markdown-ish draft
        for raw_line in draft.split("\n"):
            line = raw_line.strip()

            if not line:
                story.append(Spacer(1, 0.25 * cm))
                continue

            # H1
            if line.startswith("# "):
                story.append(Paragraph(
                    _clean(line[2:]), title_style
                ))

            # H2
            elif line.startswith("## "):
                story.append(Paragraph(
                    _clean(line[3:]), h2_style
                ))

            # H3
            elif line.startswith("### "):
                story.append(Paragraph(
                    _clean(line[4:]), h3_style
                ))

            # Bullet
            elif line.startswith(("- ", "* ", "+ ")):
                story.append(Paragraph(
                    f"&bull;&nbsp; {_clean(line[2:])}", bullet_style
                ))

            # Numbered list
            elif len(line) > 2 and line[0].isdigit() and line[1] in ".):":
                story.append(Paragraph(
                    f"&nbsp;&nbsp;{_clean(line)}", bullet_style
                ))

            # Horizontal rule
            elif line in ("---", "***", "___"):
                story.append(HRFlowable(
                    width="100%", thickness=0.5,
                    color=colors.HexColor("#e2e8f0"),
                    spaceAfter=8,
                ))

            # Normal paragraph
            else:
                story.append(Paragraph(_clean(line), body_style))

        # Footer
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor("#e2e8f0"),
            spaceAfter=6,
        ))
        story.append(Paragraph(
            "ContentFlow AI — Automated Content Marketing Pipeline",
            footer_style
        ))

        doc.build(story)
        return buffer.getvalue()

    except ImportError:
        # reportlab not installed — return plain text as bytes
        return draft.encode("utf-8")

    except Exception:
        # Any other error — safe fallback
        return draft.encode("utf-8")


def _clean(text: str) -> str:
    """Convert basic markdown inline formatting to ReportLab XML."""
    import re
    # Bold: **text** → <b>text</b>
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Italic: *text* → <i>text</i>
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    # Inline code: `text` → just text (reportlab has no monospace inline)
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Strip leftover markdown links: [anchor](url) → anchor
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    # Escape ampersands not already in XML entities
    text = re.sub(r"&(?!(?:amp|lt|gt|quot|apos|bull|nbsp);)", "&amp;", text)
    return text