import os
import json
import base64
import tempfile
import requests
from datetime import datetime

WP_URL = os.getenv("WORDPRESS_URL", "")
WP_USER = os.getenv("WORDPRESS_USER", "")
WP_APP_PASSWORD = os.getenv("WORDPRESS_APP_PASSWORD", "")

class PublisherAgent:
    name = "Publisher"

    def run(self, seo_data: dict, visual_data: dict, research: dict, run_id: int) -> dict:
        """
        Assembles final HTML page and optionally publishes to WordPress.
        Always saves a local HTML file as fallback/download.
        """
        final_html = self._assemble(seo_data, visual_data, research)
        filename = f"content_{run_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        # ✅ FIX: Use Windows-compatible temp directory
        temp_dir = tempfile.gettempdir()
        filepath = os.path.join(temp_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(final_html)

        wp_result = None
        if WP_URL and WP_USER and WP_APP_PASSWORD:
            wp_result = self._publish_wordpress(seo_data, final_html)

        return {
            "filepath": filepath,
            "filename": filename,
            "html": final_html,
            "wordpress": wp_result,
            "published_at": datetime.now().isoformat()
        }

    def _assemble(self, seo_data: dict, visual_data: dict, research: dict) -> str:
        meta_title = seo_data.get("meta_title", "Blog Post")
        meta_desc = seo_data.get("meta_description", "")
        body = seo_data.get("optimized_content", "")
        img_html = visual_data.get("html_embeds", "")
        keywords_str = ", ".join(research.get("keywords", []))

        # Inject first image after first <h2> or <p>
        if img_html and "<h2" in body:
            idx = body.find("</h2>") + 5
            body = body[:idx] + "\n" + img_html.split("</figure>")[0] + "</figure>\n" + body[idx:]

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{meta_title}</title>
  <meta name="description" content="{meta_desc}"/>
  <meta name="keywords" content="{keywords_str}"/>
  <meta property="og:title" content="{meta_title}"/>
  <meta property="og:description" content="{meta_desc}"/>
  <style>
    body {{ font-family: Georgia, serif; max-width: 820px; margin: 0 auto; padding: 2rem 1.5rem;
            color: #1a1a1a; line-height: 1.8; background: #fafaf8; }}
    h1 {{ font-size: 2.2rem; color: #111; margin-bottom: 0.5rem; }}
    h2 {{ font-size: 1.5rem; color: #222; margin-top: 2rem; border-left: 4px solid #4f46e5;
           padding-left: 0.75rem; }}
    p {{ margin: 1rem 0; }}
    a {{ color: #4f46e5; }}
    ul, ol {{ padding-left: 1.5rem; }}
    li {{ margin: 0.4rem 0; }}
    strong {{ color: #111; }}
    figure img {{ max-width: 100%; border-radius: 8px; }}
    .meta {{ font-size: 0.85rem; color: #666; margin-bottom: 2rem; }}
    .cta-box {{ background: #4f46e5; color: white; padding: 1.5rem; border-radius: 10px;
                 margin-top: 2.5rem; text-align: center; }}
    .cta-box a {{ color: #fff; font-weight: bold; }}
    @media(max-width:600px) {{ h1 {{ font-size:1.5rem; }} h2 {{ font-size:1.2rem; }} }}
  </style>
</head>
<body>
  <div class="meta">Generated by ContentFlow AI &bull; {datetime.now().strftime('%B %d, %Y')}</div>
  {body}
  <div class="cta-box">
    <p style="margin:0 0 0.5rem;">Found this helpful? Share it with your team!</p>
    <a href="#">← Back to Blog</a>
  </div>
</body>
</html>"""

    def _publish_wordpress(self, seo_data: dict, html: str) -> dict:
        try:
            creds = base64.b64encode(f"{WP_USER}:{WP_APP_PASSWORD}".encode()).decode()
            headers = {"Authorization": f"Basic {creds}", "Content-Type": "application/json"}
            payload = {
                "title": seo_data.get("meta_title", "New Post"),
                "content": html,
                "status": "draft",
                "excerpt": seo_data.get("meta_description", "")
            }
            r = requests.post(f"{WP_URL.rstrip('/')}/wp-json/wp/v2/posts",
                              headers=headers, json=payload, timeout=15)
            data = r.json()
            return {"success": True, "post_id": data.get("id"), "link": data.get("link")}
        except Exception as e:
            return {"success": False, "error": str(e)}